export const translations = [
  { english: 'Me/I', mandarin: 'Wǒ', characters: '我' },
  { english: 'You', mandarin: 'Nǐ', characters: '你' },
  { english: 'Him/Her', mandarin: 'Tā', characters: '他' },
  { english: 'We/Us', mandarin: 'Wǒmen', characters: '我们' },
  { english: 'You (Multiple people)', mandarin: 'Nǐmen', characters: '你们' },
  { english: 'They', mandarin: 'Tāmen', characters: '他们' },
  { english: 'Ours', mandarin: 'Wǒmen de', characters: '我们的' },
  { english: "How's your day going", mandarin: 'Nǐ jīntiānguò dé zěnyàng', characters: '你今天过得怎样' },
  { english: 'Hello', mandarin: 'Nǐ hǎo', characters: '你好' },
  { english: 'One', mandarin: 'Yī', characters: '一' },
  { english: 'Two', mandarin: 'Èr / Liǎng', characters: '二', info: 'Use Èr as "second" (The second month), use Liǎng as "Two" (Two Months Until...)' },
  { english: 'Three', mandarin: 'Sān', characters: '三' },
  { english: 'Four', mandarin: 'Sì', characters: '四' },
  { english: 'Five', mandarin: 'Wǔ', characters: '五' },
  { english: 'Six', mandarin: 'Liù', characters: '六' },
  { english: 'Seven', mandarin: 'Qī', characters: '七' },
  { english: 'Eight', mandarin: 'Bā', characters: '八' },
  { english: 'Nine', mandarin: 'Jiǔ', characters: '九' },
  { english: 'Ten', mandarin: 'Shí', characters: '十' },
  { english: 'Umbrella', mandarin: 'Yǔsǎn', characters: '雨伞' },
  { english: 'Apples', mandarin: 'Píngguǒ', characters: '苹果' },
  { english: 'Cookies', mandarin: 'Bǐnggān', characters: '饼干' },
  { english: 'Dog', mandarin: 'Gǒu', characters: '狗' },
  { english: 'Turkey', mandarin: 'Huǒ jī', characters: '火鸡' },
  { english: 'Onion', mandarin: 'Yángcōng', characters: '洋葱' },
  { english: 'Cat', mandarin: 'Māo', characters: '猫' },
  { english: 'Socks', mandarin: 'Wàzi', characters: '袜子' },
  { english: 'Water', mandarin: 'Shuǐ', characters: '水' },
  { english: 'Guitar', mandarin: 'Jítā', characters: '吉他' },
  { english: 'Truck', mandarin: 'Kǎchē', characters: '卡车' },
  { english: 'Chair', mandarin: 'Yǐzi', characters: '椅子' },


]