export const translations =
{
  conversation: [
    { english: 'Hello', mandarin: 'Nǐ hǎo', characters: '你好' },
    { english: 'How are you', mandarin: 'Nǐ hǎo ma', characters: '你好嗎' },
    { english: "I'm good", mandarin: 'Wǒ hěn hǎo', characters: '我很好' },
    { english: "I'm not good", mandarin: 'Wǒ bù hǎo', characters: '我不好' },
    { english: "How's your day going", mandarin: 'Nǐ jīntiānguò dé hǎo ma', characters: '你今天过得好嗎' },
    { english: "Not bad", mandarin: 'Hái hǎo', characters: '還好' },
    { english: "What are you doing", mandarin: 'Nǐ zài gànshénme', characters: '你在幹什麼' },
    { english: "How is LuLu Doing", mandarin: 'LuLu hǎo ma', characters: '好嗎' },
    { english: "Good Morning", mandarin: 'Zǎo ān', characters: '早安' },
    { english: "Good Night", mandarin: 'Wǎn ān', characters: '晚安' },
    { english: "What is your name", mandarin: 'Nǐ jiào shénme míngzì', characters: '你叫什麼名字' },
    { english: "My Name is", mandarin: 'Wǒ de míngzì shì', characters: '我的名字是' },
    { english: "Happy to meet you", mandarin: 'Hěn gāoxìng jiàn dào nǐ', characters: '很高興見到你' },
    { english: "I'm learning Chinese", mandarin: 'Wǒ zài xué zhōngwén', characters: '我在學中文' },
    { english: "I Want", mandarin: 'Wǒ yào', characters: '我要' },
    { english: "Excuse me", mandarin: 'Bù hǎo yìsi', characters: '不好意思' },
  ],
  numbers: [
    { english: 'Numbers', mandarin: 'Shùzì', characters: '數字' },
    { english: 'One', mandarin: 'Yī', characters: '一' },
    { english: 'Two', mandarin: 'Èr / Liǎng', characters: '二' },
    { english: 'Three', mandarin: 'Sān', characters: '三' },
    { english: 'Four', mandarin: 'Sì', characters: '四' },
    { english: 'Five', mandarin: 'Wǔ', characters: '五' },
    { english: 'Six', mandarin: 'Liù', characters: '六' },
    { english: 'Seven', mandarin: 'Qī', characters: '七' },
    { english: 'Eight', mandarin: 'Bā', characters: '八' },
    { english: 'Nine', mandarin: 'Jiǔ', characters: '九' },
    { english: 'Ten', mandarin: 'Shí', characters: '十' },
    { english: 'Hundred', mandarin: 'Bǎi', characters: '百' },
    { english: 'Ninety Nine', mandarin: 'Jiǔshíjiǔ', characters: '九十九' },
    { english: 'Twenty Seven', mandarin: 'Èrshíqī', characters: '二十七' },
    { english: 'Seven Hundred Fifty One', mandarin: 'Qībǎi wǔshíyī', characters: '七百五十一' },
    { english: 'Three Hundred Eighty Six', mandarin: 'Sānbǎi bāshíliù', characters: '三百八十六' },
  ],
  colors: [
    { english: 'Colors', mandarin: 'Yán sè', characters: '顏色' },
    { english: 'Red', mandarin: 'Hóng sè', characters: '紅色' },
    { english: 'Yellow', mandarin: 'Huáng sè', characters: '黃色' },
    { english: 'Brown', mandarin: 'Zōng sè', characters: '棕色' },
    { english: 'Black', mandarin: 'Hēi sè', characters: '黑色' },
    { english: 'Purple', mandarin: 'Zǐ sè', characters: '紫色' },
    { english: 'Blue', mandarin: 'Lán sè', characters: '藍色' },
    { english: 'Green', mandarin: 'Lǜ sè', characters: '綠色' },
    { english: 'White', mandarin: 'Bái sè', characters: '白色' },
    { english: 'Orange', mandarin: 'Chéng sè', characters: '橙色' },
    { english: 'Pink', mandarin: 'Fěn sè', characters: '粉色' },
    { english: 'Grey', mandarin: 'Huī sè', characters: '灰色' },
  ],
  animals: [
    { english: 'Dog', mandarin: 'Gǒu', characters: '狗' },
    { english: 'Cat', mandarin: 'Māo', characters: '猫' },
    { english: 'Turkey', mandarin: 'Huǒ jī', characters: '火鸡' },
    { english: 'Monkey', mandarin: 'Hóu', characters: '猴' },
    { english: 'Gorilla', mandarin: 'Dà xīngxīng', characters: '大猩猩' },
    { english: 'Chicken', mandarin: 'Jī', characters: '雞' },
    { english: 'Mouse', mandarin: 'Lǎoshǔ', characters: '老鼠' },
  ],
  food: [
    { english: 'Apples', mandarin: 'Píngguǒ', characters: '苹果' },
    { english: 'Cookies', mandarin: 'Bǐnggān', characters: '饼干' },
    { english: 'Onion', mandarin: 'Yángcōng', characters: '洋葱' },
    { english: 'Water', mandarin: 'Shuǐ', characters: '水' },
  ],
  shapes: [
    { english: 'Shapes', mandarin: 'Xíngzhuàng', characters: '形狀' },
    { english: 'Circle', mandarin: 'Yuán xíng', characters: '圓圈' },
    { english: 'Rectangle', mandarin: 'Chángfāng xíng', characters: '長方形' },
    { english: 'Square', mandarin: 'Zhèngfāng xíng', characters: '正方形' },
    { english: 'Triangle', mandarin: 'Sānjiǎo xíng', characters: '三角形' },
  ],
  instruments: [
    { english: 'Instruments', mandarin: 'Yíqì', characters: '儀器' },
    { english: 'Guitar', mandarin: 'Jítā', characters: '吉他' },
    { english: 'Piano', mandarin: 'Gāngqín', characters: '鋼琴' },
    { english: 'Drum', mandarin: 'Gǔ', characters: '鼓' },
  ],
  transport: [
    { english: 'Car', mandarin: 'Chē', characters: '車' },
    { english: 'Truck', mandarin: 'Kǎchē', characters: '卡車' },
    { english: 'Bicycle', mandarin: 'Zìxíngchē', characters: '自行車' },
    { english: 'Bus', mandarin: 'Gōngchē', characters: '卡车' },
    { english: 'Train', mandarin: 'Huǒchē', characters: '火車' },
    { english: 'Airplane', mandarin: 'Fēijī', characters: '飛機' },

  ],
  pronouns: [
    { english: 'Me/I', mandarin: 'Wǒ', characters: '我' },
    { english: 'You', mandarin: 'Nǐ', characters: '你' },
    { english: 'Him/Her', mandarin: 'Tā', characters: '他' },
    { english: 'We/Us', mandarin: 'Wǒmen', characters: '我们' },
    { english: 'You (Multiple people)', mandarin: 'Nǐmen', characters: '你们' },
    { english: 'They', mandarin: 'Tāmen', characters: '他们' },
    { english: 'Ours', mandarin: 'Wǒmen de', characters: '我们的' },
    { english: 'Yours', mandarin: 'Nǐ de', characters: '你的' },
  ],
  other: [
    { english: 'Umbrella', mandarin: 'Yǔsǎn', characters: '雨伞' },
    { english: 'Socks', mandarin: 'Wàzi', characters: '袜子' },
    { english: 'Chair', mandarin: 'Yǐzi', characters: '椅子' },
    { english: 'Box', mandarin: 'Hézi', characters: '盒子' },
    { english: 'Scissors', mandarin: 'Jiǎndāo', characters: '剪刀' },
    { english: 'Books', mandarin: 'Túshū', characters: '圖書' },
    { english: 'Pencil', mandarin: 'Qiānbǐ', characters: '鉛筆' },
    { english: 'Clock', mandarin: 'Zhōng', characters: '鐘' },
    { english: 'Shirt', mandarin: 'Chènshān', characters: '襯衫' },
    { english: 'Pants', mandarin: 'Kùzi', characters: '褲子' },
    { english: 'Hat', mandarin: 'Màozi', characters: '帽子' },
    { english: 'Clothing', mandarin: 'Fúzhuāng', characters: '服裝' },
  ]
}