export const translations =
{
  greetings: [
    { english: "How's your day going", mandarin: 'Nǐ jīntiānguò dé zěnyàng', characters: '你今天过得怎样' },
    { english: 'Hello', mandarin: 'Nǐ hǎo', characters: '你好' },
  ],
  numbers: [
    { english: 'Numbers', mandarin: 'Shùzì', characters: '數字' },
    { english: 'One', mandarin: 'Yī', characters: '一' },
    { english: 'Two', mandarin: 'Èr / Liǎng', characters: '二' },
    { english: 'Three', mandarin: 'Sān', characters: '三' },
    { english: 'Four', mandarin: 'Sì', characters: '四' },
    { english: 'Five', mandarin: 'Wǔ', characters: '五' },
    { english: 'Six', mandarin: 'Liù', characters: '六' },
    { english: 'Seven', mandarin: 'Qī', characters: '七' },
    { english: 'Eight', mandarin: 'Bā', characters: '八' },
    { english: 'Nine', mandarin: 'Jiǔ', characters: '九' },
    { english: 'Ten', mandarin: 'Shí', characters: '十' },
    { english: 'Hundred', mandarin: 'Bǎi', characters: '百' },
    { english: 'Ninety Nine', mandarin: 'Jiǔshíjiǔ', characters: '九十九' },
    { english: 'Twenty Seven', mandarin: 'Èrshíqī', characters: '二十七' },
    { english: 'Seven Hundred Fifty One', mandarin: 'Qībǎi wǔshíyī', characters: '七百五十一' },
    { english: 'Three Hundred Eighty Six', mandarin: 'Sānbǎi bāshíliù', characters: '三百八十六' },
  ],
  colors: [
    { english: 'Colors', mandarin: 'Yán sè', characters: '顏色' },
    { english: 'Red', mandarin: 'Hóng sè', characters: '紅色' },
    { english: 'Yellow', mandarin: 'Huáng sè', characters: '黃色' },
    { english: 'Brown', mandarin: 'Zōng sè', characters: '棕色' },
    { english: 'Black', mandarin: 'Hēi sè', characters: '黑色' },
    { english: 'Purple', mandarin: 'Zǐ sè', characters: '紫色' },
    { english: 'Blue', mandarin: 'Lán sè', characters: '藍色' },
    { english: 'Green', mandarin: 'Lǜ sè', characters: '綠色' },
    { english: 'White', mandarin: 'Bái sè', characters: '白色' },
    { english: 'Orange', mandarin: 'Chéng sè', characters: '橙色' },
    { english: 'Pink', mandarin: 'Fěn sè', characters: '粉色' },
    { english: 'Grey', mandarin: 'Huī sè', characters: '灰色' },
  ],
  animals: [
    { english: 'Cat', mandarin: 'Māo', characters: '猫' },
    { english: 'Turkey', mandarin: 'Huǒ jī', characters: '火鸡' },
    { english: 'Dog', mandarin: 'Gǒu', characters: '狗' },
  ],
  food: [
    { english: 'Apples', mandarin: 'Píngguǒ', characters: '苹果' },
    { english: 'Cookies', mandarin: 'Bǐnggān', characters: '饼干' },
    { english: 'Onion', mandarin: 'Yángcōng', characters: '洋葱' },
    { english: 'Water', mandarin: 'Shuǐ', characters: '水' },
  ],
  other: [
    { english: 'Umbrella', mandarin: 'Yǔsǎn', characters: '雨伞' },
    { english: 'Socks', mandarin: 'Wàzi', characters: '袜子' },
    { english: 'Guitar', mandarin: 'Jítā', characters: '吉他' },
    { english: 'Truck', mandarin: 'Kǎchē', characters: '卡车' },
    { english: 'Chair', mandarin: 'Yǐzi', characters: '椅子' },
    { english: 'Me/I', mandarin: 'Wǒ', characters: '我' },
    { english: 'You', mandarin: 'Nǐ', characters: '你' },
    { english: 'Him/Her', mandarin: 'Tā', characters: '他' },
    { english: 'We/Us', mandarin: 'Wǒmen', characters: '我们' },
    { english: 'You (Multiple people)', mandarin: 'Nǐmen', characters: '你们' },
    { english: 'They', mandarin: 'Tāmen', characters: '他们' },
    { english: 'Ours', mandarin: 'Wǒmen de', characters: '我们的' },
  ]
}